"use client";
import { useEffect, useState } from "react";
import { Megaphone, Package, Plus, UserPlus } from "lucide-react";
import { api, post, patch } from "../lib/api";
import type { Client, User } from "../lib/types";

type Product = { id: string; code: string; name: string; description: string; priceMinor: number; currency: string; active: boolean };
type Campaign = { id: string; name: string; description: string; startsAt: string; endsAt: string | null; active: boolean; products: { product: Product; priceMinor: number }[]; enrollments: { client: { id: string; name: string }; advisor: { id: string; name: string }; status: string }[] };
export function Catalog({ commercial, clients }: { commercial: boolean; clients: Client[] }) {
  const [products, setProducts] = useState<Product[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [error, setError] = useState(""); const [showProduct, setShowProduct] = useState(false); const [showCampaign, setShowCampaign] = useState(false);
  const load = async () => { try { setError(""); const [p, c] = await Promise.all([api<Product[]>("/catalog/products"), api<Campaign[]>("/catalog/campaigns")]); setProducts(p); setCampaigns(c); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, []);
  async function createProduct(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await post("/catalog/products", { code: f.get("code"), name: f.get("name"), description: f.get("description") ?? "", priceMinor: Number(f.get("priceMinor")), currency: "COP", active: true }); setShowProduct(false); await load(); } catch (e) { setError((e as Error).message); } }
  async function createCampaign(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await post("/catalog/campaigns", { name: f.get("name"), description: f.get("description") ?? "", startsAt: new Date(String(f.get("startsAt"))).toISOString(), endsAt: null, active: true, productIds: [] }); setShowCampaign(false); await load(); } catch (e) { setError((e as Error).message); } }
  async function enroll(campaignId: string, clientId: string) { try { await post(`/catalog/campaigns/${campaignId}/enroll`, { clientId }); await load(); } catch (e) { setError((e as Error).message); } }
  return <div className="catalog-view">{error && <div className="error" role="alert">{error}</div>}<div className="catalog-actions">{commercial && <><button className="primary" onClick={() => setShowProduct(true)}><Plus size={16}/>Producto</button><button className="secondary" onClick={() => setShowCampaign(true)}><Megaphone size={16}/>Campaña</button></>}</div><div className="catalog-grid"><section className="panel"><div className="section-heading"><h2><Package size={18}/> Catálogo <span className="badge">{products.length}</span></h2></div>{products.length ? products.map(p => <article className="catalog-row" key={p.id}><div><strong>{p.name}</strong><small>{p.code} · {p.description}</small></div><b>${p.priceMinor.toLocaleString("es-CO")} {p.currency}</b></article>) : <p className="hint">Aún no hay productos.</p>}</section><section className="panel"><div className="section-heading"><h2><Megaphone size={18}/> Campañas <span className="badge">{campaigns.length}</span></h2></div>{campaigns.length ? campaigns.map(c => <article className="campaign-card" key={c.id}><strong>{c.name}</strong><small>{c.description || "Sin descripción"}</small><span className="badge">{c.enrollments.length} clientes</span>{commercial && clients.length > 0 && <select className="catalog-enroll" defaultValue="" onChange={e => { if (e.target.value) void enroll(c.id, e.target.value); }}><option value="">Agregar cliente…</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select>}</article>) : <p className="hint">Crea una campaña para reactivar clientes.</p>}</section></div>{showProduct && <dialog open className="dialog"><form className="dialog-card" onSubmit={createProduct}><h2>Nuevo producto</h2><input name="code" required placeholder="Código"/><input name="name" required placeholder="Nombre"/><input name="description" placeholder="Descripción"/><input name="priceMinor" required type="number" min="0" placeholder="Precio en COP"/><div className="dialog-actions"><button type="button" className="secondary" onClick={() => setShowProduct(false)}>Cancelar</button><button className="primary">Guardar</button></div></form></dialog>}{showCampaign && <dialog open className="dialog"><form className="dialog-card" onSubmit={createCampaign}><h2>Nueva campaña</h2><input name="name" required placeholder="Nombre"/><input name="description" placeholder="Descripción"/><label>Inicia<input name="startsAt" required type="datetime-local"/></label><div className="dialog-actions"><button type="button" className="secondary" onClick={() => setShowCampaign(false)}>Cancelar</button><button className="primary">Guardar</button></div></form></dialog>}</div>;
}
