"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Send, ShoppingCart } from "lucide-react";
import { api, post } from "../lib/api";
import type { Client } from "../lib/types";
type Product = { id: string; name: string; code: string; priceMinor: number; active: boolean };
type Order = { id: string; status: string; totalMinor: number; currency: string; erpReference: string | null; client: { id: string; name: string }; lines: { productName: string; quantity: number; unitPriceMinor: number }[] };
export function Orders({ clients, commercial }: { clients: Client[]; commercial: boolean }) {
  const [orders, setOrders] = useState<Order[]>([]); const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState(""); const [clientId, setClientId] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState(1);
  const load = async () => { try { const [o,p] = await Promise.all([api<Order[]>("/orders"), api<Product[]>("/catalog/products")]); setOrders(o); setProducts(p); } catch (e) { setError((e as Error).message); } }; useEffect(() => { void load(); }, []);
  async function create() { if (!clientId || !productId) return; try { const result = await post<Order>("/orders", { clientId, idempotencyKey: crypto.randomUUID(), lines: [{ productId, quantity }] }); setClientId(""); setProductId(""); setQuantity(1); await load(); return result; } catch (e) { setError((e as Error).message); } }
  async function submit(id: string) { try { await post(`/orders/${id}/submit`, {}); await load(); } catch (e) { setError((e as Error).message); } }
  return <section className="panel orders-view">{error && <div className="error" role="alert">{error}</div>}<div className="section-heading"><div><h2><ShoppingCart size={18}/> Pedidos <span className="badge">{orders.length}</span></h2><p>El precio queda congelado al crear el borrador.</p></div></div><div className="order-create"><select value={clientId} onChange={e => setClientId(e.target.value)}><option value="">Cliente…</option>{clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={productId} onChange={e => setProductId(e.target.value)}><option value="">Producto…</option>{products.filter(p => p.active).map(p => <option key={p.id} value={p.id}>{p.name} · ${p.priceMinor.toLocaleString("es-CO")}</option>)}</select><input type="number" min={1} max={10000} value={quantity} onChange={e => setQuantity(Number(e.target.value))}/><button className="primary" onClick={() => void create()} disabled={!clientId || !productId}><ShoppingCart size={16}/> Crear borrador</button></div>{orders.length ? orders.map(o => <article className="order-row" key={o.id}><div><strong>{o.client.name}</strong><small>{o.lines.map(l => `${l.productName} × ${l.quantity}`).join(", ")}</small></div><b>${o.totalMinor.toLocaleString("es-CO")} {o.currency}</b><span className="badge">{o.status === "sent" ? `Enviado ${o.erpReference ?? ""}` : o.status}</span>{o.status !== "sent" && commercial && <button className="secondary" onClick={() => void submit(o.id)}><Send size={15}/> Enviar ERP</button>}{o.status === "sent" && <CheckCircle2 className="order-ok" size={18}/>}</article>) : <p className="hint">Aún no hay pedidos.</p>}</section>;
}
