export const routes = [
  ["POST", "/auth/register", "register", false],
  ["POST", "/auth/login", "login", false],
  ["POST", "/auth/accept-invitation", "acceptInvitation", false],
  ["POST", "/auth/logout", "logout", true],
  ["GET", "/auth/me", "me", true],
  ["GET", "/organization", "organization", true],
  ["GET", "/users", "users", true],
  ["GET", "/invitations", "invitations", true],
  ["POST", "/invitations", "invite", true],
  ["GET", "/clients", "clients", true],
  ["POST", "/clients", "createClient", true],
  ["PATCH", "/clients/:id/assignment", "reassignClient", true],
  ["GET", "/clients/:id/history", "history", true],
  ["GET", "/activities", "activities", true],
  ["POST", "/activities", "createActivity", true],
  ["POST", "/activities/:id/start-visit", "startVisit", true],
  ["POST", "/activities/:id/complete", "completeActivity", true],
  ["GET", "/development/mailbox", "mailbox", true],
  ["GET", "/billing/settings", "billingSettings", true],
  ["PATCH", "/billing/settings", "updateBillingSettings", true],
  ["POST", "/billing/quote", "billingQuote", true],
  ["POST", "/billing/checkout", "billingCheckout", true],
  ["GET", "/billing/payments/:reference", "billingPayment", true],
  ["POST", "/billing/simulations", "billingSimulate", true],
  ["GET", "/billing/simulations", "billingHistory", true],
  ["POST", "/platform/whatsapp-numbers", "platformRegisterNumber", true],
  ["GET", "/platform/whatsapp-numbers", "platformListNumbers", true],
  [
    "POST",
    "/platform/whatsapp-numbers/:id/verify",
    "platformVerifyNumber",
    true,
  ],
  ["GET", "/platform/organizations", "platformOrganizations", true],
  [
    "PATCH",
    "/platform/organizations/:id/modules",
    "platformUpdateModules",
    true,
  ],
  ["GET", "/whatsapp/numbers", "whatsappNumbers", true],
  ["PATCH", "/whatsapp/numbers/:id/assignment", "whatsappAssign", true],
  ["GET", "/whatsapp/conversations", "whatsappConversations", true],
  ["GET", "/whatsapp/conversations/:id/messages", "whatsappMessages", true],
  ["POST", "/whatsapp/conversations/:id/messages", "whatsappSend", true],
  [
    "POST",
    "/whatsapp/conversations/:id/templates",
    "whatsappSendTemplate",
    true,
  ],
  ["GET", "/webhooks/whatsapp", "whatsappWebhookVerify", false, true],
  ["POST", "/webhooks/whatsapp", "whatsappWebhookEvents", false, true],
  ["POST", "/webhooks/wompi", "wompiWebhookEvents", false, true],
] as const;
