export const routes = [
  ["POST", "/auth/register", "register", false],
  ["POST", "/auth/login", "login", false],
  ["POST", "/auth/accept-invitation", "acceptInvitation", false],
  ["POST", "/auth/logout", "logout", true],
  ["GET", "/auth/me", "me", true],
  ["GET", "/organization", "organization", true],
  ["GET", "/users", "users", true],
  ["GET", "/invitations", "invitations", true],
  ["POST", "/invitations", "invite", true],
  ["GET", "/clients", "clients", true],
  ["POST", "/clients", "createClient", true],
  ["PATCH", "/clients/:id/assignment", "reassignClient", true],
  ["GET", "/clients/:id/history", "history", true],
  ["GET", "/activities", "activities", true],
  ["POST", "/activities", "createActivity", true],
  ["POST", "/activities/:id/complete", "completeActivity", true],
  ["GET", "/development/mailbox", "mailbox", true],
  ["GET", "/billing/settings", "billingSettings", true],
  ["PATCH", "/billing/settings", "updateBillingSettings", true],
  ["POST", "/billing/quote", "billingQuote", true],
  ["POST", "/billing/simulations", "billingSimulate", true],
  ["GET", "/billing/simulations", "billingHistory", true],
] as const;
